line_length:
- 150 # warning
- 200 # error

identifier_name:
  min_length:
    warning: 2

opt_in_rules:
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- conditional_returns_on_newline
- contains_over_first_not_nil
- empty_count
- explicit_init
- fatal_error_message
- first_where
- implicit_return
- joined_default_parameter
- overridden_super_call
- redundant_nil_coalescing
- sorted_first_last
- switch_case_on_newline

excluded:
- Core/Shared/Appearance/Generated # Zeplin doesn't generate nice code
- Pods

disabled_rules:
- nesting # Currently can't be adjusted so would already complain for 2nd level nesting
- switch_case_alignment # Keep this disabled if you like to ident case lines inside a switch statement